### ISSUE TITLE
Numerical results between this implementation and Instant-NGP

### ISSUE THREAD

**Issue by wen-yuan-zhang** [Hanlin-Zhou/PyTorch-InstantNGP#1]
Thanks for your excellent work! I am well aware that this job is not easy. I wonder what are the numerical metrics of the reprocduced code? For example, can it achieve comparable results to the raw implementation of instant-ngp on the nerf lego dataset?

**Comment by Hanlin-Zhou** [comment]
Sadly its around 10 times slower for gigapixel, and 50 to 100 times slower for nerf to converge to similar results visually. This repo is just a naive pytorch implementation for study purpose, so not quite comparable to the offical code which uses all kinds of acceration techniques like OptiX, DLSS, Cutlass CUDA, etc..
