### ISSUE TITLE
the version of nerfacc

### ISSUE THREAD

**Issue by coollzd** [Hanlin-Zhou/PyTorch-InstantNGP#2]
I meet the error “nerfacc has no ray_marching”.
so I wonder the correct version of nerfacc.
Which version do you use?

**Comment by Zhaohx424** [comment]
Hi, did you solve this problem? I meet the same problem that : module 'nerfacc' has no attribute 'ray_marching'.

**Comment by Hanlin-Zhou** [comment]
try nerfacc 0.3.0.
if still doesnt work then try 0.3.1 or 0.2.4
I dont have the local file with me right now, so i am not totally sure.
or you can change the ray_marching part of the code to work with newest nerfacc version, whatever the new function is called, it is most likely more optimized.
